# simple_ortho configuration
camera:
  name: Integraph DMC             # Not used
  focal_len: 120.                 # Focal length in mm
  sensor_size: [92.160, 165.888]  # Sensor/CCD [width, height] dimensions in mm

ortho:
  dem_interp: cubic_spline  # Interpolation type for resampling DEM (average, bilinear, cubic, cubic_spline, gauss, lanczos)
  dem_band: 1               # 1-based index of band in DEM raster to use
  interp: nearest           # Interpolation type for generating ortho-image (nearest, average, bilinear, cubic, lanczos)
  resolution: [0.5, 0.5]    # Output pixel size [x, y] in m
  compression: deflate      # GeoTIFF compression type (deflate, jpeg, jpeg2000, lzw, zstd, none)
  interleave: band          # Interleave by 'pixel' or 'band' (pixel, band)
  photometric:              # Photometric interpretation, see https://gdal.org/drivers/raster/gtiff.html for options (None = same format as source image, recommended)
  tile_size: [512, 512]     # Tile/block [x, y] size in pixels  ([512, 512] recommended)
  nodata: 0                 # NODATA value
  per_band: False           # Remap the source raster to the ortho per-band (True), or all bands at once (False - recommended)
  driver: GTiff             # Format of ortho raster - see www.gdal.org/formats_list.html (None = same format as source image)
  dtype:                    # Data type of ortho raster (e.g. uint8, uint16, float32 etc)  (None = same type as source image)
  build_ovw: True           # Build internal overviews
  overwrite: True           # Overwrite ortho raster if it exists
  write_mask: True          # Write an internal mask band (True), can help remove jpeg noise in nodata area (False - recommended)
