# simple-ortho configuration
camera:
  # Not used
  name: Integraph DMC
  # Camera model type (pinhole, brown, fisheye, opencv)
  type: pinhole
  # Image [width, height] in pixels
  im_size: [7680, 13824]
  # Focal length in same units/scale as `sensor_size` - can be single value or [x, y] pair.
  focal_len: 120.
  # Optional sensor [width, height] in same units/scale as `focal_len`.  If omitted, `focal_len` should be normalised
  # and unitless: `focal_len` = (focal length) / (sensor width).
  sensor_size: [92.160, 165.888]
  # Optional distortion coefficients according to camera `type`. See the readme for details.
  #   brown: k1, k2, p1, p2, k3, cx, cy
  #   fisheye: k1, k2, k3, k4
  #   opencv: k1, k2, p1, p2, k3, k4, k5, k6, s1, s2, s3, s4


ortho:
  # CRS of the ortho image and camera positions as an EPSG, proj4 or WKT string.  Can be omitted if the source image has a CRS.
  crs:
  # Interpolation type for resampling DEM (average, bilinear, cubic, cubic_spline, gauss, lanczos)
  dem_interp: cubic
  # 1-based index of band in DEM raster to use
  dem_band: 1
  # Interpolation type for generating ortho-image (nearest, average, bilinear, cubic, lanczos)
  interp: nearest
  # Remap the source raster to the ortho per-band (True), or all bands at once (False - recommended)
  per_band: False
  # Build internal overviews
  build_ovw: True
  # Overwrite ortho raster if it exists
  overwrite: True
  # Write an internal mask band (True), can help remove jpeg noise in nodata area (False - recommended)
  write_mask: False
  # Remap source to ortho with full camera model (True), or undistorted source to ortho with pinhole model (False).
  full_remap: True
  # Format of ortho raster - see www.gdal.org/formats_list.html (None = same format as source image)
  dtype:
  # Output pixel size [x, y] in m
  resolution: [0.5, 0.5]
  # Compress type (deflate, jpeg, auto)
  compress: auto
