name: Tests (conda-forge)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # run weekly

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.9', '3.11', '3.12']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        activate-environment: orthority-test
        conda-solver: libmamba

    - name: Run unit tests
      run: |
        python -m pytest --cov=orthority --cov-report=term-missing --cov-report=xml:coverage.xml ./tests
